from . import add_genre
from . import add_operator
from . import add_region
from . import add_song
from . import all_users
from . import ban_user
from . import change_card
from . import change_link
from . import change_price
from . import change_song
from . import change_status
from . import channel_statistic
from . import confirm_payment
from . import do_it
from . import doubters_users
from . import get_admin_menu
from . import how_much_have_link
from . import how_much_pay
from . import non_subscription_users
from . import overdue_users
from . import search_non_users
from . import search_user
from . import suggest_songs
from . import users_tariffs
